### PR TITLE
Rename `CRM\Campaign` namespace to avoid collisions with new Core extension

### LINKED ISSUE #110: Namespace conflict with campaign core component
Since CiviCRM version 5.63.0

References:
- GitLab-Issue [Proposal: Create stub extensions for civicrm core + all components](https://lab.civicrm.org/dev/core/-/issues/3961)
   - included: [namespace communication](https://lab.civicrm.org/dev/core/-/issues/3961#note_92824)
- GitLab-Issue: [Meta: Create list of items for moving a core component to an extension](https://lab.civicrm.org/dev/core/-/issues/3089)
- GitHub-PR: [dev/core#3961 Create stub extensions for all components](https://github.com/civicrm/civicrm-core/pull/26036)
- GitHub-PR: [dev/core#3961 - Modify psr-0 namespaces of component extensions to match core](https://github.com/civicrm/civicrm-core/pull/26256)

_ref: 21638_

### PR DESCRIPTION
**Pull request by jensschuppe**
See [dev/core#3961](https://lab.civicrm.org/dev/core/-/issues/3961#note_92824)

* [x] Release a version before merging this, stating the incompatibility with *CiviCRM Core* `>=5.63.0`
* [x] Rename namespace `CRM\Campaign` to `CRM\CampaignManager`
* [x] ~~Check whether `<file>campaign</file>` should be changed as well (the *Core* extension has `<file>civi_campaign</file>`)~~
* [x] ~~Check whether renaming the extension/repository would be feasible~~
* [x] Release a version after merging this ~~including upgrader or steps to upgrade, if the extension name changes~~

### CODE REVIEW

**Comment by jensschuppe** [comment]
@sluc23 happy to receive your review!

**Comment by sluc23** [comment]
overall looks good.. only apiv3 `campaign_expense_get` looks like not working, but could be an pre-existing issue

**Comment by jensschuppe** [comment]
@sluc23 Thanks a lot for testing - would you be able to verify your assumption about the `campaign_expense_get` problem not being caused by this PR?

We'll try to merge this soon anyway.

**Comment by sluc23** [comment]
seems to be something else, not related to this PR.. you can move forwards with the merging.. we will keep testing it when you release a new version in our web sites. tx!

**Comment by jensschuppe** [comment]
This has been released with version 1.4-alpha1.

**Comment by colemanw** [comment]
@jensschuppe I'm hearing reports about this crash and reports are going to increase now that CiviCRM has a security update forcing people to upgrade. It looks like they are not upgrading this module to 1.4 because it's marked `alpha`.

**Comment by jensschuppe** [comment]
I just released [1.4.0](https://github.com/systopia/de.systopia.campaign/releases/tag/1.4.0). Thanks for the hint!

**Comment by colemanw** [comment]
Great thanks @jensschuppe

**Pull request merged**
