### PR TITLE
Fix bug about inheritance between campaigns

### PR DESCRIPTION
**Pull request by scardinius**
There was a problem with reporting KPI on different levels of campaigns. 
On higher level wasn't visible values from lower levels.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @scardinius and thank you for your contribution. I will merge this PR when I get a chance to talk to Björn (@systopia)

**Comment by michau** [comment]
Hey guys, any news here? :-) We're about to contribute some more and wondering if we should contribute directly or work on a fork. :-)

**Comment by bjendres** [comment]
Hi @michau. Thanks for the PR, sorry this got delayed during the holidays. @nikobo will look into this soon, he just wanted to verify that it's not changing the behaviour in an unwanted way.

**Comment by michau** [comment]
No problem about the delay, we'll wait for verification.

**Comment by ghost** [comment]
@scardinius, @michau 
Thank you for the bug fix

**Pull request merged**
