### PR TITLE
Civix code upgrade to Civix version 23.02.1

### PR DESCRIPTION
**Pull request by jensschuppe**
This extension seems to be using some non-standard methods for installing/enabling, so this Civix upgrade should be checked in those scenarios before merging. But it should definitely go into a stable `1.3` release.

### CODE REVIEW

**Comment by bjendres** [comment]
I don't think I can review this. Shouldn't we just try it to see if it works correctly...?

**Comment by jensschuppe** [comment]
> I don't think I can review this. Shouldn't we just try it to see if it works correctly...?

GitHub was suggesting you for that :stuck_out_tongue: ... I'd be happy with releasing it in the next beta and let the universe try.

**Comment by jofranz** [comment]
@jensschuppe @bjendres How should we progress here?

**Comment by jensschuppe** [comment]
@jofranz I went ahead merging this, thanks for the reminder!

**Pull request merged**
