### PR TITLE
Fix ROI type from number to percentage

### PR DESCRIPTION
**Pull request by scardinius**
Small fix. I think that `ROI` should be presented as a percentage, the same as a `Total Revenue Reached`. That's right?

### CODE REVIEW

**Comment by bjendres** [comment]
I think we had a discussion about that, and we decided for a factor... 

@Fabian-SYSTOPIA: Can you remember why?

**Comment by Fabian-SYSTOPIA** [comment]
I think the only reason is that (at least in Germany) it is common in Fundraising to display it that way.

**Comment by scardinius** [comment]
This is your decision what you want to do with this PR :-)

**Comment by bjendres** [comment]
@Fabian-SYSTOPIA: Do you want to keep it as a factor? Do you care at all?

**Comment by Fabian-SYSTOPIA** [comment]
I honestly don't have an oppinion about that ^^

**Comment by bjendres** [comment]
Suits me :)

Thanks again, @scardinius

**Pull request merged**
