### PR TITLE
Fix name of custom KPIs hook

### PR DESCRIPTION
**Pull request by scardinius**
Hi,

In order to implement my custom KPI I needed to fix a name of hook. 
The name has to be proper in utils and in documentation for user.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you!

**Comment by bjendres** [comment]
@scardinius: Thanks. Two things, though:
- is there a particular reason why you renamed the hook to `campaignKpis`?
- I think the documentation should rather say `hook_civicrm_campaignKpis...``, since this is the format used throughout [CiviCRM's hook reference](https://wiki.civicrm.org/confluence/display/CRMDOC/Hook+Reference). I changed that just now.

**Comment by scardinius** [comment]
- I changed `campaign_kpis` to `campaignKpis` because of camelCase convention used in [CiviCRM's hook reference](https://wiki.civicrm.org/confluence/display/CRMDOC/Hook+Reference).
- I agreed with you that `hook_*` looks like a example and is compatible with Hook Reference.

**Comment by bjendres** [comment]
> I changed campaign_kpis to campaignKpis because of camelCase convention used in CiviCRM's hook reference.

Fair enough. I just hope not a lot of people are using this atm. But I don't think so :)

**Pull request merged**
